### ISSUE TITLE
restrictive upper bound on base

### ISSUE THREAD

**Issue by maralorn** [srid/ema#156]
See: https://hydra.nixos.org/build/228038654/nixlog/1/tail

**Comment by lucasvreis** [comment]
More generally, dependency bounds of ema-related packages (including lvar and unionmount) are not following https://pvp.haskell.org/. In most cases bounds should be of the form `>= x.x.x && < x.x`

**Comment by srid** [comment]
Happy to accept PRs adding those version bounds. I have just been lazy in this regard because these packages are pinned by Nix.

I'll make a new release of Ema, emanote, heist-extra, extra with these changes.

**Comment by maralorn** [comment]
> Happy to accept PRs adding those version bounds. I have just been lazy in this regard because these packages are pinned by Nix.

Yeah, I know. I was actually wondering whether there is something you/we can do to be more preemptive on bounds.
To be honest [this comment I wrote a while ago on the Haskell discours](https://discourse.haskell.org/t/dependency-version-bounds-are-a-lie/5522/41) mainly relates to my experience maintaining your packages, because you are such a Nix power user.

**Comment by srid** [comment]
https://github.com/srid/ema/commit/3c96f445ebd8b278d82e91237a3157e418279ad0

(I just noticed that my 'forever' relaxation is not applied to all .cabal packages; will address that latter)
