### ISSUE TITLE
stack also works

### ISSUE THREAD

**Issue by juhp** [srid/ema#53]
I know nix is getting attention but not everyone (including me) uses it...
and in fact stack also works fine I think for running this project.

Would you accept a PR to add stack.yaml and an explanation for how to run with stack?
It should be pretty simple.

**Comment by srid** [comment]
> The problem with adding stack.yaml to the repo however is that it can soon become out of date with no maintainer to fix it (I don't use stack myself). We could perhaps add instructions to README, or even better - add a new page under https://ema.srid.ca/guide ?

Having seen no response to this, I'll unmark this as an actionable issue (by transferring it to Discussions), as I'm unwilling to take on non-Nix maintenance.
