### ISSUE TITLE
Change window.location.hash; and test in web browsers

### ISSUE THREAD

**Issue by srid** [srid/ema#85]
_Originally posted by @srid in https://github.com/srid/ema/pull/83#discussion_r807496211_

**Comment by srid** [comment]
I merged this without reviewing the new diff.

**Comment by lucasvreis** [comment]
@srid sorry, while in the PR I did explain my intentions with this line (trigger the hashchange event), this seems only to work with Firefox. The correct line is `window.dispatchEvent(new HashChangeEvent("hashchange"))`. (I'm not a developer, so sorry again).

**Comment by srid** [comment]
@lucasvreis No worries; [responded here](https://github.com/srid/ema/pull/83#discussion_r808030806). I appreciate your PR!

You have an interesting project going [here](https://github.com/lucasvreis/manguezal); will that be available for general use?
